<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Team;
use App\Models\Seat;
use App\Models\Player;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

         User::factory()->create([
             'name' => 'Admin User',
             'email' => 'admin@example.com',
	        'is_admin' => true,
	        'password' => '12345678910',
         ]);

        // insert team info
        Team::insert([
        [
            'name' => 'Dallas Mavericks',
            'city' => 'Dallas',
            'abbreviation' => 'DAL',
            'logo' => 'images/teams/Dallas_Mavericks_logo.svg',
            'conference' => 'Western',
            'division' => 'Southwest',
            'wins' => 2,
            'losses' => 2,
            'arena' => 'American Airlines Center',
        ],
        [
            'name' => 'Los Angeles Lakers',
            'city' => 'Los Angeles',
            'abbreviation' => 'LAL',
            'logo' => 'images/teams/Los_Angeles_Lakers_logo.svg',
            'conference' => 'Western',
            'division' => 'Pacific',
            'wins' => 4,
            'losses' => 2,
            'arena' => 'Crypto.com Arena',
        ],
        [
            'name' => 'New York Knicks',
            'city' => 'New York',
            'abbreviation' => 'NYK',
            'logo' => 'images/teams/NYK_logo.svg',
            'conference' => 'Eastern',
            'division' => 'Atlantic',
            'wins' => 7,
            'losses' => 0,
            'arena' => 'Madison Square Garden',
        ],
        [
            'name' => 'Oklahoma City Thunder',
            'city' => 'Oklahoma City',
            'abbreviation' => 'OKC',
            'logo' => 'images/teams/Oklahoma_City_Thunder.svg',
            'conference' => 'Western',
            'division' => 'Northwest',
            'wins' => 5,
            'losses' => 2,
            'arena' => 'Paycom Center',
        ],
        [
            'name' => 'San Antonio Spurs',
            'city' => 'San Antonio',
            'abbreviation' => 'SAS',
            'logo' => 'images/teams/San_Antonio_Spurs.svg',
            'conference' => 'Western',
            'division' => 'Southwest',
            'wins' => 7,
            'losses' => 0,
            'arena' => 'Frost Bank Center',
        ],
        ]);

        Player::insert([
            [
                'pfp' => 'images/players/max.avif',
                'name' => 'Max Christie',
                'team' => 'Dallas Mavericks',
                'height' => "6'5",
                'weight'=> '190 lbs',
                'country' => 'USA',
                'age' => '23',
                'yearspro' => '3',
                'points' => '20', 
                'rebounds' => '3', 
                'assists' => '3', 
                'blocks' => '0', 
                'steals' => '0', 
                'turnovers' => '1', 
                'threepoints' => '2', 
                'freethrows' => '2', 
                'fantasy' => '30.1'
            ],
            [
                'pfp' => 'images/players/dereck.webp',
                'name' => 'Dereck Lively II',
                'team' => 'Dallas Mavericks',
                'height' => "7'1",
                'weight'=> '230 lbs',
                'country' => 'USA',
                'age' => '22',
                'yearspro' => '2',
                'points' => '24', 
                'rebounds' => '2', 
                'assists' => '4', 
                'blocks' => '2', 
                'steals' => '4', 
                'turnovers' => '1', 
                'threepoints' => '3', 
                'freethrows' => '1', 
                'fantasy' => '32.8'
            ],
            [
                'pfp' => 'images/players/dwight.webp',
                'name' => 'Dwight Powell',
                'team' => 'Dallas Mavericks',
                'height' => "6'10",
                'weight'=> '240 lbs',
                'country' => 'Canada',
                'age' => '34',
                'yearspro' => '11',
                'points' => '22', 
                'rebounds' => '1', 
                'assists' => '2', 
                'blocks' => '0', 
                'steals' => '5', 
                'turnovers' => '3', 
                'threepoints' => '1', 
                'freethrows' => '2', 
                'fantasy' => '34.2'
            ],
            [
                'pfp' => 'images/players/johnson.avif',
                'name' => 'AJ Johnson',
                'team' => 'Dallas Mavericks',
                'height' => "6'5",
                'weight'=> '160 lbs',
                'country' => 'USA',
                'age' => '21',
                'yearspro' => '1',
                'points' => '20', 
                'rebounds' => '3', 
                'assists' => '3', 
                'blocks' => '0', 
                'steals' => '0', 
                'turnovers' => '1', 
                'threepoints' => '2', 
                'freethrows' => '2', 
                'fantasy' => '31.4'
            ],
            [
                'pfp' => 'images/players/nembhard.webp',
                'name' => 'Ryan Nembhard',
                'team' => 'Dallas Mavericks',
                'height' => "5'11",
                'weight'=> '180 lbs',
                'country' => 'Canada',
                'age' => '23',
                'yearspro' => 'R',
                'points' => '23', 
                'rebounds' => '2', 
                'assists' => '4', 
                'blocks' => '1', 
                'steals' => '0', 
                'turnovers' => '2', 
                'threepoints' => '3', 
                'freethrows' => '1', 
                'fantasy' => '33.5'
            ],
            [
                'pfp' => 'images/players/Brandon.avif',
                'name' => 'Brandon Williams',
                'team' => 'Dallas Mavericks',
                'height' => "6'1",
                'weight'=> '190 lbs',
                'country' => 'USA',
                'age' => '26',
                'yearspro' => '3',
                'points' => '25', 
                'rebounds' => '4', 
                'assists' => '1', 
                'blocks' => '2', 
                'steals' => '2', 
                'turnovers' => '1', 
                'threepoints' => '2', 
                'freethrows' => '2', 
                'fantasy' => '33.7'
            ],

            [
                'pfp' => 'images/players/Deandre.avif',
                'name' => 'Deandre Ayton',
                'team' => 'Los Angeles Lakers',
                'height' => "7'0",
                'weight'=> '252 lbs',
                'country' => 'Arizona',
                'age' => '28',
                'yearspro' => '7',
                'points' => '26', 
                'rebounds' => '3', 
                'assists' => '3', 
                'blocks' => '3', 
                'steals' => '2', 
                'turnovers' => '1', 
                'threepoints' => '3', 
                'freethrows' => '2', 
                'fantasy' => '36.1'
            ],
            [
                'pfp' => 'images/players/Luka.avif',
                'name' => 'Luka Doncic',
                'team' => 'Los Angeles Lakers',
                'height' => "6'8",
                'weight'=> '230 lbs',
                'country' => 'Real Madrid',
                'age' => '27',
                'yearspro' => '7',
                'points' => '27', 
                'rebounds' => '2', 
                'assists' => '1', 
                'blocks' => '4', 
                'steals' => '1', 
                'turnovers' => '3', 
                'threepoints' => '2', 
                'freethrows' => '1', 
                'fantasy' => '37.2'
            ],
            [
                'pfp' => 'images/players/Rui.png',
                'name' => 'Rui Hachimura',
                'team' => 'Los Angeles Lakers',
                'height' => "6'8",
                'weight'=> '230 lbs',
                'country' => 'Japan',
                'age' => '28',
                'yearspro' => '6',
                'points' => '29', 
                'rebounds' => '5', 
                'assists' => '4', 
                'blocks' => '3', 
                'steals' => '3', 
                'turnovers' => '1', 
                'threepoints' => '3', 
                'freethrows' => '1', 
                'fantasy' => '38'
            ],
            [
                'pfp' => 'images/players/Jaxson.avif',
                'name' => 'Jaxson Hayes',
                'team' => 'Los Angeles Lakers',
                'height' => "7'0",
                'weight'=> '220 lbs',
                'country' => 'Texas',
                'age' => '26',
                'yearspro' => '6',
                'points' => '30', 
                'rebounds' => '1', 
                'assists' => '3', 
                'blocks' => '0', 
                'steals' => '2', 
                'turnovers' => '1', 
                'threepoints' => '4', 
                'freethrows' => '2', 
                'fantasy' => '39'
            ],
            [
                'pfp' => 'images/players/Bronny.png',
                'name' => 'Bronny James',
                'team' => 'Los Angeles Lakers',
                'height' => "6'2",
                'weight'=> '210 lbs',
                'country' => 'USA',
                'age' => '22',
                'yearspro' => '1',
                'points' => '33', 
                'rebounds' => '1', 
                'assists' => '3', 
                'blocks' => '4', 
                'steals' => '2', 
                'turnovers' => '3', 
                'threepoints' => '2', 
                'freethrows' => '2', 
                'fantasy' => '34.3'
            ],
            [
                'pfp' => 'images/players/Lebron.png',
                'name' => 'Lebron James',
                'team' => 'Los Angeles Lakers',
                'height' => "6'9",
                'weight'=> '250 lbs',
                'country' => 'USA',
                'age' => '42',
                'yearspro' => '22',
                'points' => '37', 
                'rebounds' => '5', 
                'assists' => '7', 
                'blocks' => '7', 
                'steals' => '8', 
                'turnovers' => '5', 
                'threepoints' => '4', 
                'freethrows' => '5', 
                'fantasy' => '37.5'
            ],

            [
                'pfp' => 'images/players/Clarkson.webp',
                'name' => 'Jordan Clarkson',
                'team' => 'New York Knicks',
                'height' => "6'5",
                'weight'=> '194 lbs',
                'country' => 'USA',
                'age' => '34',
                'yearspro' => '11',
                'points' => '35', 
                'rebounds' => '2', 
                'assists' => '4', 
                'blocks' => '3', 
                'steals' => '5', 
                'turnovers' => '3', 
                'threepoints' => '2', 
                'freethrows' => '2', 
                'fantasy' => '35'
            ],
            [
                'pfp' => 'images/players/Miles.png',
                'name' => 'Miles McBride',
                'team' => 'New York Knicks',
                'height' => "6'2",
                'weight'=> '195 lbs',
                'country' => 'USA',
                'age' => '25',
                'yearspro' => '4',
                'points' => '33.4', 
                'rebounds' => '2', 
                'assists' => '3', 
                'blocks' => '4', 
                'steals' => '1', 
                'turnovers' => '3', 
                'threepoints' => '2', 
                'freethrows' => '1', 
                'fantasy' => '32.1'
            ],
            [
                'pfp' => 'images/players/Josh.png',
                'name' => 'Josh Hart',
                'team' => 'New York Knicks',
                'height' => "6'5",
                'weight'=> '215 lbs',
                'country' => 'USA',
                'age' => '31',
                'yearspro' => '8',
                'points' => '31', 
                'rebounds' => '2', 
                'assists' => '4', 
                'blocks' => '1', 
                'steals' => '3', 
                'turnovers' => '5', 
                'threepoints' => '4', 
                'freethrows' => '2', 
                'fantasy' => '33.9'
            ],
            [
                'pfp' => 'images/players/Pacome.webp',
                'name' => 'Pacome Dadiet',
                'team' => 'New York Knicks',
                'height' => "6'9",
                'weight'=> '210 lbs',
                'country' => 'France',
                'age' => '20',
                'yearspro' => '1',
                'points' => '29', 
                'rebounds' => '2', 
                'assists' => '1', 
                'blocks' => '0', 
                'steals' => '2', 
                'turnovers' => '1', 
                'threepoints' => '2', 
                'freethrows' => '2', 
                'fantasy' => '32.3'
            ],
            [
                'pfp' => 'images/players/Jose.avif',
                'name' => 'Jose Alvarado',
                'team' => 'New York Knicks',
                'height' => "6'0",
                'weight'=> '179 lbs',
                'country' => 'USA',
                'age' => '28',
                'yearspro' => '4',
                'points' => '28', 
                'rebounds' => '4', 
                'assists' => '2', 
                'blocks' => '3', 
                'steals' => '3', 
                'turnovers' => '2', 
                'threepoints' => '1', 
                'freethrows' => '2', 
                'fantasy' => '32.3'
            ],
            [
                'pfp' => 'images/players/OG.png',
                'name' => 'OG Anunoby',
                'team' => 'New York Knicks',
                'height' => "6'7",
                'weight'=> '240 lbs',
                'country' => 'United Kingdom',
                'age' => '28',
                'yearspro' => '8',
                'points' => '25', 
                'rebounds' => '4', 
                'assists' => '3', 
                'blocks' => '2', 
                'steals' => '3', 
                'turnovers' => '4', 
                'threepoints' => '1', 
                'freethrows' => '2', 
                'fantasy' => '34.1'
            ],

            [
                'pfp' => 'images/players/Shail.webp',
                'name' => 'Shai Gilgeous-Alexander',
                'team' => 'Oklahoma City Thunder',
                'height' => "6'6",
                'weight'=> '195 lbs',
                'country' => 'Canada',
                'age' => '27',
                'yearspro' => '7',
                'points' => '27', 
                'rebounds' => '5', 
                'assists' => '2', 
                'blocks' => '3', 
                'steals' => '0', 
                'turnovers' => '2', 
                'threepoints' => '1', 
                'freethrows' => '2', 
                'fantasy' => '35.1'
            ],
            [
                'pfp' => 'images/players/mccain.png',
                'name' => 'Jared McCain',
                'team' => 'Oklahoma City Thunder',
                'height' => "6'3",
                'weight'=> '195 lbs',
                'country' => 'USA',
                'age' => '22',
                'yearspro' => '1',
                'points' => '31', 
                'rebounds' => '2', 
                'assists' => '3', 
                'blocks' => '4', 
                'steals' => '1', 
                'turnovers' => '2', 
                'threepoints' => '2', 
                'freethrows' => '3', 
                'fantasy' => '33.1'
            ],
            [
                'pfp' => 'images/players/Luguentz.webp',
                'name' => 'Luguentz Dort',
                'team' => 'Oklahoma City Thunder',
                'height' => "6'4",
                'weight'=> '220 lbs',
                'country' => 'Canada',
                'age' => '27',
                'yearspro' => '6',
                'points' => '20', 
                'rebounds' => '3', 
                'assists' => '3', 
                'blocks' => '0', 
                'steals' => '0', 
                'turnovers' => '1', 
                'threepoints' => '2', 
                'freethrows' => '2', 
                'fantasy' => '34.2'
            ],
            [
                'pfp' => 'images/players/Jaylin.png',
                'name' => 'Jaylin Williams',
                'team' => 'Oklahoma City Thunder',
                'height' => "6'9",
                'weight'=> '240 lbs',
                'country' => 'USA',
                'age' => '23',
                'yearspro' => '3',
                'points' => '29', 
                'rebounds' => '4', 
                'assists' => '3', 
                'blocks' => '4', 
                'steals' => '1', 
                'turnovers' => '3', 
                'threepoints' => '2', 
                'freethrows' => '1', 
                'fantasy' => '35.3'
            ],
            [
                'pfp' => 'images/players/Chet.webp',
                'name' => 'Chet Holmgren',
                'team' => 'Oklahoma City Thunder',
                'height' => "7'1",
                'weight'=> '208 lbs',
                'country' => 'USA',
                'age' => '24',
                'yearspro' => '2',
                'points' => '29', 
                'rebounds' => '4', 
                'assists' => '4', 
                'blocks' => '1', 
                'steals' => '0', 
                'turnovers' => '3', 
                'threepoints' => '2', 
                'freethrows' => '2', 
                'fantasy' => '37.2'
            ],
            [
                'pfp' => 'images/players/Jalen_Williams.png',
                'name' => 'Jalen Williams',
                'team' => 'Oklahoma City Thunder',
                'height' => "6'5",
                'weight'=> '211 lbs',
                'country' => 'USA',
                'age' => '25',
                'yearspro' => '3',
                'points' => '25', 
                'rebounds' => '2', 
                'assists' => '1', 
                'blocks' => '3', 
                'steals' => '1', 
                'turnovers' => '3', 
                'threepoints' => '2', 
                'freethrows' => '2', 
                'fantasy' => '34.5'
            ],

            [
                'pfp' => 'images/players/McLaughlin.webp',
                'name' => 'Jordan McLaughlin',
                'team' => 'San Antonio Spurs',
                'height' => "5'11",
                'weight'=> '185 lbs',
                'country' => 'USA',
                'age' => '30',
                'yearspro' => '6',
                'points' => '28', 
                'rebounds' => '2', 
                'assists' => '4', 
                'blocks' => '3', 
                'steals' => '2', 
                'turnovers' => '3', 
                'threepoints' => '2', 
                'freethrows' => '3', 
                'fantasy' => '32.1'
            ],
            [
                'pfp' => 'images/players/Victor.avif',
                'name' => 'Victor Wembanyama',
                'team' => 'San Antonio Spurs',
                'height' => "7'4",
                'weight'=> '235 lbs',
                'country' => 'France',
                'age' => '22',
                'yearspro' => '2',
                'points' => '29', 
                'rebounds' => '4', 
                'assists' => '3', 
                'blocks' => '5', 
                'steals' => '2', 
                'turnovers' => '1', 
                'threepoints' => '2', 
                'freethrows' => '4', 
                'fantasy' => '29.8'
            ],
            [
                'pfp' => 'images/players/Dylan.avif',
                'name' => 'Dylan Harper',
                'team' => 'San Antonio Spurs',
                'height' => "6'5",
                'weight'=> '215 lbs',
                'country' => 'USA',
                'age' => '20',
                'yearspro' => 'R',
                'points' => '29', 
                'rebounds' => '5', 
                'assists' => '3', 
                'blocks' => '4', 
                'steals' => '2', 
                'turnovers' => '4', 
                'threepoints' => '2', 
                'freethrows' => '3', 
                'fantasy' => '37.7'
            ],
            [
                'pfp' => 'images/players/Keldon.webp',
                'name' => 'Keldon Johnson',
                'team' => 'San Antonio Spurs',
                'height' => "6'6",
                'weight'=> '220 lbs',
                'country' => 'USA',
                'age' => '26',
                'yearspro' => '6',
                'points' => '33', 
                'rebounds' => '5', 
                'assists' => '4', 
                'blocks' => '3', 
                'steals' => '3', 
                'turnovers' => '2', 
                'threepoints' => '4', 
                'freethrows' => '2', 
                'fantasy' => '35.3'
            ],
            [
                'pfp' => "images/players/De'Aaron.avif",
                'name' => "De'Aaron Fox",
                'team' => 'San Antonio Spurs',
                'height' => "6'3",
                'weight'=> '185 lbs',
                'country' => 'USA',
                'age' => '28',
                'yearspro' => '8',
                'points' => '32', 
                'rebounds' => '3', 
                'assists' => '4', 
                'blocks' => '1', 
                'steals' => '2', 
                'turnovers' => '1', 
                'threepoints' => '2', 
                'freethrows' => '3', 
                'fantasy' => '34.3'
            ],
            [
                'pfp' => 'images/players/Stephon_Castle.png',
                'name' => 'Stephon Castle',
                'team' => 'San Antonio Spurs',
                'height' => "6'6",
                'weight'=> '215 lbs',
                'country' => 'USA',
                'age' => '21',
                'yearspro' => '1',
                'points' => '34', 
                'rebounds' => '4', 
                'assists' => '2', 
                'blocks' => '3', 
                'steals' => '1', 
                'turnovers' => '2', 
                'threepoints' => '2', 
                'freethrows' => '1', 
                'fantasy' => '32.5'
            ]
        ]);
    }
}
